export const DASHBOARD_PRODUCTS_REQUEST = " DASHBOARD_PRODUCTS_REQUEST";
export const DASHBOARD_PRODUCTS_SUCCESS = " DASHBOARD_PRODUCTS_SUCCESS";
export const DASHBOARD_PRODUCTS_FAIL = " DASHBOARD_PRODUCTS_FAIL";
